### ISSUE TITLE
unexpected interaction with corsica-video

### ISSUE THREAD

**Issue by lonnen** [mythmon/corsica-google-presentation#3]
```
command {
  raw: 'gslide id=1faZ-uoAd3Zg7voYM90GxAM7BFqn4xPcKxb88ws9HHQs comment="nice tweets" screen=ambient1'
}
TypeError: content.url.endsWith is not a function
    at /Users/lonnen/repos/moz-corsica/node_modules/corsica-video/index.js:26:21
    at invokeCallback (/Users/lonnen/repos/moz-corsica/node_modules/es6-promise/dist/es6-promise.js:408:15)
    at publish (/Users/lonnen/repos/moz-corsica/node_modules/es6-promise/dist/es6-promise.js:391:7)
    at flush (/Users/lonnen/repos/moz-corsica/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
```

This is quite unexpected. The error implies that `content.url` is not a string.

**Comment by lonnen** [comment]
Some local debugging. It is indeed a function. The error probably lies in the 'non-business corsica' bits outside the test suite.

**Comment by lonnen** [comment]
Found it. The slide building function function was being passed directly instead of being initialized with the deckID to create the necessary closure. Incoming PR
